config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :medicine_intake_logs
  resources :doctor_notifications
  resources :user_vital_logs
  resources :in_patients
  resources :prescribed_medicines do
    get 'filtered', :on => :collection
  end
  resources :prescriptions
  resources :medicines
  resources :doctor_appointments
  resources :doctors do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end
  resources :users do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end
  get 'user_vital_summary', to: 'user_vital_summary#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'home#index'
end

app/models/medicine.rb
class Medicine < ApplicationRecord
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :set_medicine, only: [:show, :edit, :update, :destroy]

  # GET /medicines
  # GET /medicines.json
  def index
    @medicines = Medicine.all
  end

  # GET /medicines/1
  # GET /medicines/1.json
  def show
  end

  # GET /medicines/new
  def new
    @medicine = Medicine.new
  end

  # GET /medicines/1/edit
  def edit
  end

  # POST /medicines
  # POST /medicines.json
  def create
    @medicine = Medicine.new(medicine_params)

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, notice: 'Medicine was successfully created.' }
        format.json { render :show, status: :created, location: @medicine }
      else
        format.html { render :new }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicines/1
  # PATCH/PUT /medicines/1.json
  def update
    respond_to do |format|
      if @medicine.update(medicine_params)
        format.html { redirect_to @medicine, notice: 'Medicine was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicine }
      else
        format.html { render :edit }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1
  # DELETE /medicines/1.json
  def destroy
    @medicine.destroy
    respond_to do |format|
      format.html { redirect_to medicines_url, notice: 'Medicine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicine
      @medicine = Medicine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicine_params
      params.require(:medicine).permit(:name, :description, :medicine_type, :is_acidic, :infant_safe)
    end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/medicines/_form.html.erb
<%= form_with(model: medicine, class: 'pure-form pure-form-aligned', local: true) do |form| %>
  <% if medicine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medicine.errors.count, "error") %> prohibited this medicine from being saved:</h2>

      <ul>
      <% medicine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field pure-control-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :medicine_name %>
  </div>

  <div class="field pure-control-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :medicine_description %>
  </div>

  <div class="field pure-control-group">
    <%= form.label :medicine_type %>
    <%= form.text_field :medicine_type, id: :medicine__medicine_type %>
  </div>

  <div class="field pure-control-group">
    <%= form.label :is_acidic %>
    <%= form.check_box :is_acidic, id: :medicine_is_acidic %>
  </div>

  <div class="field pure-control-group">
    <%= form.label :infant_safe %>
    <%= form.check_box :infant_safe, id: :medicine_infant_safe %>
  </div>

  <div class="actions">
    <%= form.submit 'submit', :class => 'pure-button'%>
  </div>
<% end %>

app/views/medicines/edit.html.erb
<h1>Editing Medicine</h1>

<%= render 'form', medicine: @medicine %>

<%= link_to 'Show', @medicine, class: 'pure-button  pure-button-primary'  %> |
<%= link_to 'Back', medicines_path, class: 'pure-button  button-secondary'  %>

app/views/medicines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medicines</h1>

<table class="pure-table pure-table-bordered">
  <thead>
    <tr class="<%= cycle('pure-table-odd', '') -%>">
      <th>Name</th>
      <th>Description</th>
      <th>Type</th>
      <th>Is acidic</th>
      <th>Infant safe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicines.each do |medicine| %>
      <tr class="<%= cycle('pure-table-odd', '') -%>">
        <td><%= medicine.name %></td>
        <td><%= medicine.description %></td>
        <td><%= medicine.medicine_type %></td>
        <td><%= medicine.is_acidic %></td>
        <td><%= medicine.infant_safe %></td>
        <td><%= link_to 'Show', medicine, class: 'pure-button  pure-button-primary'  %></td>
        <td><%= link_to 'Edit', edit_medicine_path(medicine), class: 'pure-button  button-secondary'  %></td>
        <td><%= link_to 'Destroy', medicine, method: :delete, data: { confirm: 'Are you sure?' }, class: 'pure-button  button-warning'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medicine', new_medicine_path, class: 'pure-button  button-secondary'  %>

app/views/medicines/new.html.erb
<h1>New Medicine</h1>

<%= render 'form', medicine: @medicine %>

<%= link_to 'Back', medicines_path, class: 'pure-button  button-secondary'  %>

app/views/medicines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @medicine.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @medicine.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @medicine.medicine_type %>
</p>

<p>
  <strong>Is acidic:</strong>
  <%= @medicine.is_acidic %>
</p>

<p>
  <strong>Infant safe:</strong>
  <%= @medicine.infant_safe %>
</p>

<%= link_to 'Edit', edit_medicine_path(@medicine), class: 'pure-button  pure-button-primary'  %> |
<%= link_to 'Back', medicines_path, class: 'pure-button  button-secondary'  %>