config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :medicine_intake_logs
  resources :doctor_notifications
  resources :user_vital_logs
  resources :in_patients
  resources :prescribed_medicines do
    get 'filtered', :on => :collection
  end
  resources :prescriptions
  resources :medicines
  resources :doctor_appointments
  resources :doctors do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end
  resources :users do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end
  get 'user_vital_summary', to: 'user_vital_summary#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'home#index'
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
  has_many :prescribed_medicines
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :set_prescription, only: [:show, :edit, :update, :destroy]
  before_action :set_doctors_and_users, only: [:new, :edit]
  before_action :set_doctor_user_from_session, only: [:index, :new]

  # GET /prescriptions
  # GET /prescriptions.json
  def index
    if @doctor && @user
      @prescriptions = Prescription.where(user_id: @user.id, doctor_id: @doctor.id)
    elsif @doctor
      @prescriptions = Prescription.where(doctor_id: @doctor.id)
    elsif @user
      @prescriptions = Prescription.where(user_id: @user.id)
    else
      @prescriptions = Prescription.all
    end
  end

  # GET /prescriptions/1
  # GET /prescriptions/1.json
  def show
  end

  # GET /prescriptions/new
  def new
    @prescription = Prescription.new
  end

  # GET /prescriptions/1/edit
  def edit
  end

  # POST /prescriptions
  # POST /prescriptions.json
  def create
    @prescription = Prescription.new(prescription_params)

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to @prescription, notice: 'Prescription was successfully created.' }
        format.json { render :show, status: :created, location: @prescription }
      else
        format.html { render :new }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prescriptions/1
  # PATCH/PUT /prescriptions/1.json
  def update
    respond_to do |format|
      if @prescription.update(prescription_params)
        format.html { redirect_to @prescription, notice: 'Prescription was successfully updated.' }
        format.json { render :show, status: :ok, location: @prescription }
      else
        format.html { render :edit }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prescriptions/1
  # DELETE /prescriptions/1.json
  def destroy
    @prescription.destroy
    respond_to do |format|
      format.html { redirect_to prescriptions_url, notice: 'Prescription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prescription
      @prescription = Prescription.find(params[:id])
    end

    def set_doctors_and_users
      @doctors = Doctor.all
      @users = User.all
    end

    def set_doctor_user_from_session
      #initialise ids
      doctor_id = nil
      user_id = nil

      # find user
      if session[:user_id]
        user_id = session[:user_id]
      elsif request.query_parameters['userId']
        user_id = request.query_parameters['userId']
      end
      if user_id
        @user = User.find(user_id)
      end

      # find doctor
      if session[:doctor_id]
        doctor_id = session[:doctor_id]
      elsif request.query_parameters['doctorId']
        doctor_id = request.query_parameters['doctorId']
      end
      if doctor_id
        @doctor = Doctor.find(doctor_id)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prescription_params
      params.require(:prescription).permit(:user_id, :doctor_id, :notes, :prescribed_on, :valid_till)
    end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/_form.html.erb
<%= form_with(model: prescription, class: 'pure-form pure-form-aligned', local: true) do |form| %>
  <% if prescription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prescription.errors.count, "error") %> prohibited this prescription from being saved:</h2>

      <ul>
      <% prescription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if @doctor %>
    <div class="field pure-control-group">Doctor: <%= @doctor.first_name %>&nbsp;<%= @doctor.last_name %></div>
    <%= form.hidden_field :doctor_id, :value => @doctor.id%>
  <% else %>
    <div class="field pure-control-group">
      <%= form.label :doctor_id %>
      <%= form.select :doctor_id, options_for_select(@doctors.map{ |d| [d.first_name+' '+d.last_name, d.id, {'username'=>d.username}] }, selected_key = form.object.doctor_id) %>
    </div>
  <% end %>

  <% if @user %>
    <div class="field pure-control-group">User: <%= @user.first_name %>&nbsp;<%= @user.last_name %></div>
    <%= form.hidden_field :user_id, :value => @user.id%>
  <% else %>
    <div class="field pure-control-group">
      <%= form.label :user_id %>
      <%= form.select :user_id, options_for_select(@users.map{ |u| [u.first_name+' '+u.last_name, u.id, {'username'=>u.username}] }, selected_key = form.object.user_id) %>
    </div>
  <% end %>

  <div class="field pure-control-group">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :prescription_notes %>
  </div>

  <div class="field pure-control-group">
    <%= form.label :prescribed_on %>
    <%= form.datetime_select :prescribed_on, id: :prescription_prescribed_on %>
  </div>

  <div class="field pure-control-group">
    <%= form.label :valid_till %>
    <%= form.datetime_select :valid_till, id: :prescription_valid_till %>
  </div>

  <div class="actions">
    <%= form.submit 'submit', :class => 'pure-button'%>
  </div>
<% end %>

app/views/prescriptions/edit.html.erb
<h1>Editing Prescription</h1>

<%= render 'form', prescription: @prescription %>

<%= link_to 'Show', @prescription, class: 'pure-button  pure-button-primary'  %> |
<%= link_to 'Back', prescriptions_path, class: 'pure-button  button-secondary'  %>

app/views/prescriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prescriptions</h1>
<% if @user %>
  <h3>User: <%= @user.first_name %>&nbsp;<%= @user.last_name %></h3>
<% end %>
<% if @doctor %>
  <h3>Doctor: <%= @doctor.first_name %>&nbsp;<%= @doctor.last_name %></h3>
<% end %>

<table class="pure-table pure-table-bordered">
  <thead>
    <tr class="<%= cycle('pure-table-odd', '') -%>">
      <th>User</th>
      <th>Doctor</th>
      <th>Notes</th>
      <th>Prescribed on</th>
      <th>Valid till</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prescriptions.each do |prescription| %>
      <tr class="<%= cycle('pure-table-odd', '') -%>">
        <td><%= prescription.user.first_name%>&nbsp;<%= prescription.user.last_name%></td>
        <td><%= prescription.doctor.first_name%>&nbsp;<%= prescription.doctor.last_name%></td>
        <td><%= prescription.notes %></td>
        <td><%= prescription.prescribed_on %></td>
        <td><%= prescription.valid_till %></td>
        <td><%= link_to 'Show', prescription, class: 'pure-button  pure-button-primary'  %></td>
        <td><%= link_to 'Edit', edit_prescription_path(prescription), class: 'pure-button  button-secondary'  %></td>
        <td><%= link_to 'Destroy', prescription, method: :delete, data: { confirm: 'Are you sure?' }, class: 'pure-button  button-warning'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prescription', new_prescription_path, class: 'pure-button  button-secondary'  %>

app/views/prescriptions/new.html.erb
<h1>New Prescription</h1>

<%= render 'form', prescription: @prescription %>

<%= link_to 'Back', prescriptions_path, class: 'pure-button  button-secondary'  %>

app/views/prescriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @prescription.user .first_name%>&nbsp;<%=@prescription.user.last_name%>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @prescription.doctor.first_name%>&nbsp;<%= @prescription.doctor.last_name%>
</p>

<p>
  <strong>Notes:</strong>
  <%= @prescription.notes %>
</p>

<p>
  <strong>Prescribed on:</strong>
  <%= @prescription.prescribed_on %>
</p>

<p>
  <strong>Valid till:</strong>
  <%= @prescription.valid_till %>
</p>
<h3>Prescribed Medicines</h3>

<table class="pure-table pure-table-bordered">
  <thead>
    <tr class="<%= cycle('pure-table-odd', '') -%>">
      <th>Medicine</th>
      <th>Prescription</th>
      <th>Notes</th>
      <th>Before breakfast</th>
      <th>After breakfast</th>
      <th>Before lunch</th>
      <th>After lunch</th>
      <th>Before dinner</th>
      <th>After dinner</th>
      <th>Available Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prescription.prescribed_medicines.each do |prescribed_medicine| %>
      <tr class="<%= cycle('pure-table-odd', '') -%>">
        <td><%= prescribed_medicine.medicine.name %></td>
        <td><%= prescribed_medicine.prescription.notes %></td>
        <td><%= prescribed_medicine.notes %></td>
        <td><%= prescribed_medicine.before_breakfast %></td>
        <td><%= prescribed_medicine.after_breakfast %></td>
        <td><%= prescribed_medicine.before_lunch %></td>
        <td><%= prescribed_medicine.after_lunch %></td>
        <td><%= prescribed_medicine.before_dinner %></td>
        <td><%= prescribed_medicine.after_dinner %></td>
        <td><%= prescribed_medicine.available_count %></td>
        <td><%= link_to 'Show', prescribed_medicine, class: 'pure-button  pure-button-primary'  %></td>
        <td><%= link_to 'Edit', edit_prescribed_medicine_path(prescribed_medicine), class: 'pure-button  button-secondary'  %></td>
        <td><%= link_to 'Destroy', prescribed_medicine, method: :delete, data: { confirm: 'Are you sure?' }, class: 'pure-button  button-warning'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>

<%= link_to 'Add Prescribed Medicine', new_prescribed_medicine_path(:prescriptionId => @prescription.id), class: 'pure-button  button-secondary' %>
<hr/>
<br/>

<%= link_to 'Edit', edit_prescription_path(@prescription), class: 'pure-button  pure-button-primary'  %> |
<%= link_to 'Back', prescriptions_path, class: 'pure-button  button-secondary'  %>