config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :medicine_intake_logs
  resources :doctor_notifications
  resources :user_vital_logs
  resources :in_patients
  resources :prescribed_medicines do
    get 'filtered', :on => :collection
  end
  resources :prescriptions
  resources :medicines
  resources :doctor_appointments
  resources :doctors do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end
  resources :users do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end
  get 'user_vital_summary', to: 'user_vital_summary#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'home#index'
end

app/models/doctor_notification.rb
class DoctorNotification < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/controllers/doctor_notifications_controller.rb
class DoctorNotificationsController < ApplicationController
  before_action :set_doctor_notification, only: [:show, :edit, :update, :destroy]
  before_action :set_doctors_and_users, only: [:new, :edit]
  before_action :set_doctor_user_from_session, only: [:index, :new]

  # GET /doctor_notifications
  # GET /doctor_notifications.json
  def index
    if @doctor && @user
      @doctor_notifications = DoctorNotification.where(doctor_id: @doctor.id, user_id: @user.id)
    elsif @user
      @doctor_notifications = DoctorNotification.where(user_id: @user.id)
    elsif @doctor
      @doctor_notifications = DoctorNotification.where(doctor_id: @doctor.id)
    else
      @doctor_notifications = DoctorNotification.all
    end
  end

  # GET /doctor_notifications/1
  # GET /doctor_notifications/1.json
  def show
  end

  # GET /doctor_notifications/new
  def new
    @doctor_notification = DoctorNotification.new
  end

  # GET /doctor_notifications/1/edit
  def edit
  end

  # POST /doctor_notifications
  # POST /doctor_notifications.json
  def create
    @doctor_notification = DoctorNotification.new(doctor_notification_params)

    respond_to do |format|
      if @doctor_notification.save
        send_notification_for_doctor_device
        # send response
        format.html { redirect_to @doctor_notification, notice: 'Doctor notification was successfully created.' }
        format.json { render :show, status: :created, location: @doctor_notification }
      else
        format.html { render :new }
        format.json { render json: @doctor_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctor_notifications/1
  # PATCH/PUT /doctor_notifications/1.json
  def update
    respond_to do |format|
      if @doctor_notification.update(doctor_notification_params)
        format.html { redirect_to @doctor_notification, notice: 'Doctor notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor_notification }
      else
        format.html { render :edit }
        format.json { render json: @doctor_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctor_notifications/1
  # DELETE /doctor_notifications/1.json
  def destroy
    @doctor_notification.destroy
    respond_to do |format|
      format.html { redirect_to doctor_notifications_url, notice: 'Doctor notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor_notification
      @doctor_notification = DoctorNotification.find(params[:id])
    end

    def set_doctors_and_users
      @doctors = Doctor.all
      @users = User.all
    end

    def set_doctor_user_from_session
      #initialise ids
      doctor_id = nil
      user_id = nil

      # find user
      if session[:user_id]
        user_id = session[:user_id]
      elsif request.query_parameters['userId']
        user_id = request.query_parameters['userId']
      end
      if user_id
        @user = User.find(user_id)
      end
      # find doctor
      if session[:doctor_id]
        doctor_id = session[:doctor_id]
      elsif request.query_parameters['doctorId']
        doctor_id = request.query_parameters['doctorId']
      end
      if doctor_id
        @doctor = Doctor.find(doctor_id)
      end
    end

    def send_notification_for_doctor_device
      #send notification for valid selenium-webdriver
      _doctor = @doctor_notification.doctor
      if _doctor.gcmid && _doctor.gcmid.length > 10
        url = 'https://gcm-http.googleapis.com/gcm/send'
        title = "Notification(#{@doctor_notification.title}) of Patient: #{@doctor_notification.user.first_name} Severity: #{@doctor_notification.severity}"
        payload = { notification: {
              title: title,
              text: @doctor_notification.notes
            },
            to: _doctor.gcmid
          }
          # puts JSON.generate(payload)
          # puts "key="+Rails.application.secrets.gcm_server_auth_key
          # puts JSON.generate({"Content-Type" => "application/json", :Authorization => "key="+Rails.application.secrets.gcm_server_auth_key})
          resp = RestClient::Request.execute(
                 :method => :post,
                 :url => url,
                 :payload => JSON.generate(payload),
                 :headers => {"Content-Type" => "application/json", "Authorization" => "key="+Rails.application.secrets.gcm_server_auth_key}
                    )
          puts resp
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_notification_params
      params.require(:doctor_notification).permit(:title, :user_id, :doctor_id, :notified_on, :notes, :severity)
    end
end

app/helpers/doctor_notifications_helper.rb
module DoctorNotificationsHelper
end

app/views/doctor_notifications/_form.html.erb
<%= form_with(model: doctor_notification, class: 'pure-form pure-form-aligned', local: true) do |form| %>
  <% if doctor_notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor_notification.errors.count, "error") %> prohibited this doctor_notification from being saved:</h2>

      <ul>
      <% doctor_notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field pure-control-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :doctor_notification_title %>
  </div>

  <% if @doctor %>
    <div class="field pure-control-group">Doctor: <%= @doctor.first_name %>&nbsp;<%= @doctor.last_name %></div>
    <%= form.hidden_field :doctor_id, :value => @doctor.id%>
  <% else %>
    <div class="field pure-control-group">
      <%= form.label :doctor_id %>
      <%= form.select :doctor_id, options_for_select(@doctors.map{ |d| [d.first_name+' '+d.last_name, d.id, {'username'=>d.username}] }, selected_key = form.object.doctor_id) %>
    </div>
  <% end %>

  <% if @user %>
    <div class="field pure-control-group">User: <%= @user.first_name %>&nbsp;<%= @user.last_name %></div>
    <%= form.hidden_field :user_id, :value => @user.id%>
  <% else %>
    <div class="field pure-control-group">
      <%= form.label :user_id %>
      <%= form.select :user_id, options_for_select(@users.map{ |u| [u.first_name+' '+u.last_name, u.id, {'username'=>u.username}] }, selected_key = form.object.user_id) %>
    </div>
  <% end %>

  <div class="field pure-control-group">
    <%= form.label :notified_on %>
    <%= form.datetime_select :notified_on, id: :doctor_notification_notified_on %>
  </div>

  <div class="field pure-control-group">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :doctor_notification_notes %>
  </div>

  <div class="field pure-control-group">
    <%= form.label :severity %>
    <%= form.text_field :severity, id: :doctor_notification_severity %>
  </div>

  <div class="actions">
    <%= form.submit 'submit', :class => 'pure-button'%>
  </div>
<% end %>

app/views/doctor_notifications/edit.html.erb
<h1>Editing Doctor Notification</h1>

<%= render 'form', doctor_notification: @doctor_notification %>

<%= link_to 'Show', @doctor_notification %> |
<%= link_to 'Back', doctor_notifications_path %>

app/views/doctor_notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctor Notifications</h1>
<% if @user %>
  <h3>User: <%= @user.first_name %>&nbsp;<%= @user.last_name %></h3>
<% end %>
<% if @doctor %>
  <h3>Doctor: <%= @doctor.first_name %>&nbsp;<%= @doctor.last_name %></h3>
<% end %>
<table class="pure-table pure-table-bordered">
  <thead>
    <tr class="<%= cycle('pure-table-odd', '') -%>">
      <th>Title</th>
      <th>User</th>
      <th>Doctor</th>
      <th>Notified on</th>
      <th>Notes</th>
      <th>Severity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctor_notifications.each do |doctor_notification| %>
      <tr class="<%= cycle('pure-table-odd', '') -%>">
        <td><%= doctor_notification.title %></td>
        <td><%= doctor_notification.user.first_name %>&nbsp;<%= doctor_notification.user.last_name %></td>
        <td><%= doctor_notification.doctor.first_name %>&nbsp;<%= doctor_notification.doctor.last_name %></td>
        <td><%= doctor_notification.notified_on %></td>
        <td><%= doctor_notification.notes %></td>
        <td><%= doctor_notification.severity %></td>
        <td><%= link_to 'Show', doctor_notification, class: 'pure-button  pure-button-primary'  %></td>
        <td><%= link_to 'Edit', edit_doctor_notification_path(doctor_notification), class: 'pure-button  button-secondary'  %></td>
        <td><%= link_to 'Destroy', doctor_notification, method: :delete, data: { confirm: 'Are you sure?' } , class: 'pure-button  button-warning' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor Notification', new_doctor_notification_path, class: 'pure-button  button-secondary'  %>

app/views/doctor_notifications/new.html.erb
<h1>New Doctor Notification</h1>

<%= render 'form', doctor_notification: @doctor_notification %>

<%= link_to 'Back', doctor_notifications_path, class: 'pure-button  button-secondary'  %>

app/views/doctor_notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @doctor_notification.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @doctor_notification.user.first_name %>&nbsp;<%= @doctor_notification.user.last_name %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @doctor_notification.doctor.first_name %>&nbsp;<%= @doctor_notification.doctor.last_name %>
</p>

<p>
  <strong>Notified on:</strong>
  <%= @doctor_notification.notified_on %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @doctor_notification.notes %>
</p>

<p>
  <strong>Severity:</strong>
  <%= @doctor_notification.severity %>
</p>

<%= link_to 'Edit', edit_doctor_notification_path(@doctor_notification), class: 'pure-button  pure-button-primary'  %> |
<%= link_to 'Back', doctor_notifications_path, class: 'pure-button  button-secondary'  %>